/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package livestock2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sujoy
 */
public class CaretakerSearchPage extends javax.swing.JFrame {

    public static Caretaker current;

    /**
     * Creates new form CaretakerSearchPage
     */
    public CaretakerSearchPage() {
        initComponents();
        tablePanel.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void showAll() {
        ArrayList<Animal> search = new ArrayList<>();
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=livestock", "sa", "123456");
            String query = "Select * from Animal Where farmId= " + current.farmId;
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            Animal temp;
            while (rs.next()) {
                temp = new Animal(rs.getInt("AnimalID"), rs.getInt("Farmid"), rs.getString("AnimalType"),
                        rs.getInt("Age"), rs.getString("RequiredMedicine"), rs.getDouble("FoodAmount"),
                        rs.getString("Gender"), rs.getInt("Weight"));
                search.add(temp);   //add animals to arraylist from database
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Object[] row = new Object[7];
        for (int i = 0; i < search.size(); i++) {
            Animal tem = search.get(i);
            row[0] = tem.animalId;
            row[1] = tem.animalType;
            row[2] = tem.age;
            row[3] = tem.requiredMedicine;
            row[4] = tem.foodAmount;
            row[5] = tem.gender;
            row[6] = tem.weight;

            model.addRow(row);
        }

    }

    private void showCow() {
        ArrayList<Animal> search = new ArrayList<>();
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=livestock", "sa", "123456");
            String query = "Select * from Animal Where farmId= " + current.farmId + "AND animaltype = 'cow'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            Animal temp;
            while (rs.next()) {
                temp = new Animal(rs.getInt("AnimalID"), rs.getInt("Farmid"), rs.getString("AnimalType"),
                        rs.getInt("Age"), rs.getString("RequiredMedicine"), rs.getDouble("FoodAmount"),
                        rs.getString("Gender"), rs.getInt("Weight"));
                search.add(temp);   //add animals to arraylist from database
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Object[] row = new Object[7];
        for (int i = 0; i < search.size(); i++) {
            Animal tem = search.get(i);
            row[0] = tem.animalId;
            row[1] = tem.animalType;
            row[2] = tem.age;
            row[3] = tem.requiredMedicine;
            row[4] = tem.foodAmount;
            row[5] = tem.gender;
            row[6] = tem.weight;

            model.addRow(row);
        }

    }

    private void showGoat() {
        ArrayList<Animal> search = new ArrayList<>();
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=livestock", "sa", "123456");
            String query = "Select * from Animal Where farmId= " + current.farmId + "AND animaltype = 'goat'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            Animal temp;
            while (rs.next()) {
                temp = new Animal(rs.getInt("AnimalID"), rs.getInt("Farmid"), rs.getString("AnimalType"),
                        rs.getInt("Age"), rs.getString("RequiredMedicine"), rs.getDouble("FoodAmount"),
                        rs.getString("Gender"), rs.getInt("Weight"));
                search.add(temp);   //add animals to arraylist from database
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Object[] row = new Object[7];
        for (int i = 0; i < search.size(); i++) {
            Animal tem = search.get(i);
            row[0] = tem.animalId;
            row[1] = tem.animalType;
            row[2] = tem.age;
            row[3] = tem.requiredMedicine;
            row[4] = tem.foodAmount;
            row[5] = tem.gender;
            row[6] = tem.weight;

            model.addRow(row);
        }

    }

    private void showSheep() {
        //callDatabase();
        ArrayList<Animal> search = new ArrayList<>();
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=livestock", "sa", "123456");
            String query = "Select * from Animal Where farmId= " + current.farmId + "AND animaltype = 'sheep'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            Animal temp;
            while (rs.next()) {
                temp = new Animal(rs.getInt("AnimalID"), rs.getInt("Farmid"), rs.getString("AnimalType"),
                        rs.getInt("Age"), rs.getString("RequiredMedicine"), rs.getDouble("FoodAmount"),
                        rs.getString("Gender"), rs.getInt("Weight"));
                search.add(temp);   //add animals to arraylist from database
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Object[] row = new Object[7];
        for (int i = 0; i < search.size(); i++) {
            Animal tem = search.get(i);
            row[0] = tem.animalId;
            row[1] = tem.animalType;
            row[2] = tem.age;
            row[3] = tem.requiredMedicine;
            row[4] = tem.foodAmount;
            row[5] = tem.gender;
            row[6] = tem.weight;

            model.addRow(row);
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        allRadioButton = new javax.swing.JRadioButton();
        cowRadioButton = new javax.swing.JRadioButton();
        goatRadioButton = new javax.swing.JRadioButton();
        sheepRadioButton = new javax.swing.JRadioButton();
        ShowButton = new javax.swing.JButton();
        tablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        clearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        radioButtonGroup.add(allRadioButton);
        allRadioButton.setText("All");
        allRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allRadioButtonActionPerformed(evt);
            }
        });
        jPanel1.add(allRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 38, 85, -1));

        radioButtonGroup.add(cowRadioButton);
        cowRadioButton.setText("Cow");
        jPanel1.add(cowRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 38, 81, -1));

        radioButtonGroup.add(goatRadioButton);
        goatRadioButton.setText("Goat");
        jPanel1.add(goatRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 38, 85, -1));

        radioButtonGroup.add(sheepRadioButton);
        sheepRadioButton.setText("Sheep");
        jPanel1.add(sheepRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 38, 85, -1));

        ShowButton.setText("Show");
        ShowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ShowButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 119, -1, -1));

        tablePanel.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Animal ID", "Animal Type", "Age", "Required Medicine", "Food Amount (gm)", "Gender", "Weight"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(100);
        }

        tablePanel.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 706, 270);

        jPanel1.add(tablePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 148, 706, 170));

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        jPanel1.add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowButtonActionPerformed

        ////////Clear Table////////
        if (allRadioButton.isSelected()) {
            showAll();

        } else if (cowRadioButton.isSelected()) {
            showCow();

        } else if (sheepRadioButton.isSelected()) {
            showSheep();

        } else if (goatRadioButton.isSelected()) {
            showGoat();
        }
    }//GEN-LAST:event_ShowButtonActionPerformed

    private void allRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allRadioButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        model.setRowCount(0);
    }//GEN-LAST:event_clearButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CaretakerSearchPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CaretakerSearchPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CaretakerSearchPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CaretakerSearchPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CaretakerSearchPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ShowButton;
    private javax.swing.JRadioButton allRadioButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JRadioButton cowRadioButton;
    private javax.swing.JRadioButton goatRadioButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.ButtonGroup radioButtonGroup;
    private javax.swing.JRadioButton sheepRadioButton;
    private javax.swing.JPanel tablePanel;
    // End of variables declaration//GEN-END:variables
}
