/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package livestock2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Sujoy
 */
public class LoginPage extends javax.swing.JFrame {

    User current;

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernametextfield = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        passwordtextfield = new javax.swing.JPasswordField();
        forgotpasswordlabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernametextfield.setBackground(new java.awt.Color(222, 120, 31));
        usernametextfield.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        usernametextfield.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(usernametextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 97, 210, 36));

        jLabel1.setBackground(new java.awt.Color(13, 21, 57));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 97, 90, 36));

        jLabel2.setBackground(new java.awt.Color(13, 21, 57));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 151, 80, 34));

        LoginButton.setBackground(new java.awt.Color(52, 178, 128));
        LoginButton.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        LoginButton.setText("Log IN");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 218, 170, 43));

        passwordtextfield.setBackground(new java.awt.Color(222, 120, 31));
        passwordtextfield.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(passwordtextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 210, 36));

        forgotpasswordlabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        forgotpasswordlabel.setForeground(new java.awt.Color(255, 255, 255));
        forgotpasswordlabel.setText("Forgot Password?");
        forgotpasswordlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotpasswordlabelMouseClicked(evt);
            }
        });
        getContentPane().add(forgotpasswordlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 130, 30));

        jPanel1.setBackground(new java.awt.Color(13, 21, 57));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LOGIN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 283, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 320));

        setSize(new java.awt.Dimension(596, 360));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logInAsCaretaker() {
        ArrayList<Caretaker> caretakerlist = new ArrayList<>();
        try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=livestock", "sa", "123456");
            String query = "Select * from Caretaker Where token= " + current.tokken;
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            Caretaker care;
            while (rs.next()) {
                care = new Caretaker(rs.getInt("caretakerID"), rs.getString("Name"), rs.getString("Contactno"), rs.getString("Email"), rs.getString("address"), rs.getInt("farmid"), rs.getInt("Token"));
                caretakerlist.add(care);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        CaretakerHomePage.token = current.tokken;
        CaretakerHomePage.current = caretakerlist.get(caretakerlist.size() - 1);

        //System.out.println(CaretakerHomePage.current.email);
        this.setVisible(false);
        new CaretakerHomePage().setVisible(true);

    }
    
    private void logInAsOwner(){
        ArrayList<Owner> ownerList = new ArrayList<>();
        try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=livestock", "sa", "123456");
            String query = "Select * from Owner Where token= " + current.tokken;
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            Owner own;
            while (rs.next()) {
                own = new Owner(rs.getInt("ownerID"), rs.getInt("Token"), 
                        rs.getString("name"), rs.getString("Address"),
                        rs.getString("Contactno"), rs.getString("Email"));
                ownerList.add(own);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        OwnerhomePage.current = ownerList.get(ownerList.size()-1);
        this.setVisible(false);
        new OwnerhomePage().setVisible(true);
    }

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        if (usernametextfield.getText().isEmpty() || passwordtextfield.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Username or Password or Sign UP");
        } else {

            String username = usernametextfield.getText();

            ArrayList<User> userlist = new ArrayList<>();
            try {

                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                Connection con = DriverManager.getConnection(
                        "jdbc:sqlserver://localhost:1433;databaseName=livestock", "sa", "123456");
                String query = "Select * from Admin Where username= '" + username + "'";
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery(query);
                User own;
                while (rs.next()) {
                    own = new User(rs.getString("Username"), rs.getString("Password"), rs.getString("UserType"), rs.getInt("Token"));
                    userlist.add(own);

                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            current = userlist.get(userlist.size() - 1);
            if (current.password.equalsIgnoreCase(passwordtextfield.getText())) {

                //run a query on caretaker table to get the detatils of the caretaker
                //using the tokken
                if (current.userType.equalsIgnoreCase("caretaker")) {
                    logInAsCaretaker();
                } else if (current.userType.equalsIgnoreCase("owner")) {
                    logInAsOwner();

                } else if (current.userType.equalsIgnoreCase("distirctlivestockofficer")) {

                }
            } else {

                JOptionPane.showMessageDialog(this, "Wrong Password");
            }
        }

    }//GEN-LAST:event_LoginButtonActionPerformed

    private void forgotpasswordlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotpasswordlabelMouseClicked
        this.setVisible(false);
        new ForgotPassword().setVisible(true);
    }//GEN-LAST:event_forgotpasswordlabelMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel forgotpasswordlabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passwordtextfield;
    private javax.swing.JTextField usernametextfield;
    // End of variables declaration//GEN-END:variables
}
