/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package livestock2;

/**
 *
 * @author Sujoy
 */
public class OwnerhomePage extends javax.swing.JFrame {
    public static Owner current;

    /**
     * Creates new form OwnerhomePage
     */
    public OwnerhomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        farmsinfo = new javax.swing.JButton();
        caretakerinfobutton = new javax.swing.JButton();
        setcaretakerbutton = new javax.swing.JButton();
        addfarmsbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        farmsinfo.setText("Farms Info.");
        farmsinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                farmsinfoActionPerformed(evt);
            }
        });

        caretakerinfobutton.setText("Caretaker info.");
        caretakerinfobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caretakerinfobuttonActionPerformed(evt);
            }
        });

        setcaretakerbutton.setText("Set Caretaker");
        setcaretakerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setcaretakerbuttonActionPerformed(evt);
            }
        });

        addfarmsbutton.setText("Add Farm");
        addfarmsbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addfarmsbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addfarmsbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(setcaretakerbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(caretakerinfobutton, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(farmsinfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(farmsinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(caretakerinfobutton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(setcaretakerbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(addfarmsbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void farmsinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_farmsinfoActionPerformed
        // TODO add your handling code here:
        ShowFarms.current = this.current;
        this.setVisible(false);
        new ShowFarms().setVisible(true);
    }//GEN-LAST:event_farmsinfoActionPerformed

    private void setcaretakerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setcaretakerbuttonActionPerformed
        // TODO add your handling code here:
        SetCaretaker.current = this.current;
        this.setVisible(false);
        new SetCaretaker().setVisible(true);
    }//GEN-LAST:event_setcaretakerbuttonActionPerformed

    private void caretakerinfobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caretakerinfobuttonActionPerformed
        // TODO add your handling code here:
        ShowCaretaker.current = this.current;
        this.setVisible(false);
        new ShowCaretaker().setVisible(true);
    }//GEN-LAST:event_caretakerinfobuttonActionPerformed

    private void addfarmsbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addfarmsbuttonActionPerformed
        // TODO add your handling code here:
        Addfarm.current = this.current;
        this.setVisible(false);
        new Addfarm().setVisible(true);
    }//GEN-LAST:event_addfarmsbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OwnerhomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OwnerhomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OwnerhomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OwnerhomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OwnerhomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addfarmsbutton;
    private javax.swing.JButton caretakerinfobutton;
    private javax.swing.JButton farmsinfo;
    private javax.swing.JButton setcaretakerbutton;
    // End of variables declaration//GEN-END:variables
}
