/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package livestock2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;

/**
 *
 * @author Sujoy
 */
public class UserType extends javax.swing.JFrame {

    /**
     * Creates new form UserType
     */
    public UserType() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        passwordTextField = new javax.swing.JTextField();
        nextTypeButton = new javax.swing.JButton();
        userTypeCheckBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(13, 21, 57));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("User Name");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 100, 33));

        jLabel2.setBackground(new java.awt.Color(13, 21, 57));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Password");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 100, 33));

        jLabel3.setBackground(new java.awt.Color(13, 21, 57));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("User Type");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 100, 29));

        userNameTextField.setBackground(new java.awt.Color(222, 120, 31));
        userNameTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        userNameTextField.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(userNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 223, 33));

        passwordTextField.setBackground(new java.awt.Color(222, 120, 31));
        passwordTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        passwordTextField.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(passwordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 223, 33));

        nextTypeButton.setBackground(new java.awt.Color(52, 178, 128));
        nextTypeButton.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        nextTypeButton.setText("Next");
        nextTypeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextTypeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(nextTypeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 227, 132, -1));

        userTypeCheckBox.setBackground(new java.awt.Color(222, 120, 31));
        userTypeCheckBox.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        userTypeCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        userTypeCheckBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DistrictLivestockOfficer", "Owner", "Caretaker" }));
        getContentPane().add(userTypeCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 223, 29));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Already have an Account? Log IN!");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 190, 20));

        jPanel2.setBackground(new java.awt.Color(13, 21, 57));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sign UP", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), java.awt.Color.white)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 263, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nextTypeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextTypeButtonActionPerformed
       try {
            
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=livestock", "sa", "123456");
            String query = "insert into admin(Username,password,userType)values(?,?,?)";
               PreparedStatement pst=con.prepareStatement(query);
               pst.setString(1, userNameTextField.getText());
               pst.setString(2, passwordTextField.getText());
               pst.setString(3, userTypeCheckBox.getSelectedItem().toString());
               pst.executeUpdate();
               this.setVisible(false);
        new SignUP().setVisible(true);
        }
         catch (Exception e) {
            e.printStackTrace();
        } 
        SignUP.userType = userTypeCheckBox.getSelectedItem().toString();
        System.out.println(SignUP.userType);
        
        
        
        
    }//GEN-LAST:event_nextTypeButtonActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new LoginPage().setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton nextTypeButton;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JTextField userNameTextField;
    private javax.swing.JComboBox userTypeCheckBox;
    // End of variables declaration//GEN-END:variables
}
